### PR TITLE
Disable struct hash<QString> declaration Qt versions greater than 5.14

### PR DESCRIPTION
**Pull request by azertyalex**
If I try to compile with a Qt version greater than 5.14 you get following compile error:  
```c++
httpServer/util.h:216:23: error: redefinition of ‘struct std::hash<QString>’
  216 |     template<> struct hash<QString>
```

### CODE REVIEW

**Comment by addisonElliott** [comment]
👍 Good catch
